### ISSUE TITLE
Create Quick Search Flask Endpoint

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-mirror#13]
- Create initial Flask app with connectors to Supabase
- Build a V1 quick search endpoint, accepting two parameters: search and county
- County should be an exact match on the county_name column in agencies table for now
- Search should be a partial match on the name column in  data_sources table (where ilike '%{}%')
- Endpoint should return a json object of the form: 
{
   "num_records": LEN(RECORDS)
   "data": {
      "data_source_name": NAME (data_sources),
      "agency_name": NAME (agencies),
      "municipality": MUNICIPALITY (agencies),
      "state": STATE_ISO (agencies),
      "description": DESCRIPTION (data_sources),
      "record_type": RECORD_TYPE (data_sources),
      "source_url": SOURCE_URL (data_sources),
      "record_format": RECORD_FORMAT (data_sources),
      "coverage_start": COVERAGE_START (data_sources),
      "coverage_end": COVERAGE_END (data_sources),
      "agency_supplied": AGENCY_SUPPLIED (data_sources)
   }
}

**Comment by kalenluciano** [comment]
I started work on initializing a Flask app and connecting it to Supabase. But I just noticed that you originally linked this issue to the data-sources-mirror repo instead of the data-sources-app repo linked in this task card here: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/1. Let me know if you want me to move my code over to the data-sources-mirror repo or keep it where it is now.

**Comment by kalenluciano** [comment]
@mbodeantor [this PR](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/3) is ready for your review. I have some notes in the comments about how it's currently working and where we might be able to improve on it.
