### ISSUE TITLE
Periodic URL archives with Save Page Now

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-mirror#7]
# The goal
- Periodically use Internet Archive's "Save Page Now" capturing service to preserve copies of Data Sources in our database. [(What is a data source?)](https://docs.pdap.io/activities/data-sources/what-is-a-data-source)
   - Log 404s, timeouts, and other errors in a file. Store the `airtable_uid`, `source_url`, and an error message as part of the log, so we can easily update the database if we can't fix the URL.

## Why?
Retention policies can be unforgiving, and important records are lost to time every day. It's bad news when a URL in our data sources database  The best time to plant a tree is 20 years ago…the second best time is now. Same here.

### But why though?
It is an incentive to give us data sources. Currently, we ask people to do it just to do us a favor or because they believe in the cause. Instead, we can say “If you know about an internet data source, submit it to us and tell us how often it’s refreshed. We will create archives automatically and link to them.” Instead of just passively storing them, we’re doing our part to preserve data. Fun!

#### Seriously, explain why this is important
It makes our data sources database more and more useful over time. That URL we saved 404s now? No worries, we archived it. Instead of becoming a useless row we need to delete, it points to a place where information was published and can still be accessed.

## Suggested approach
- [x] Make a new repository for this work (to keep this repo's purpose and function simple and clear)
   - that's here: https://github.com/Police-Data-Accessibility-Project/automatic-archives
- [x] Use this [Save Page Now Python wrapper](https://github.com/palewire/savepagenow)
- [x] https://github.com/Police-Data-Accessibility-Project/automatic-archives/issues/7

**Comment by DouglasKrouth** [comment]
I'll wait a week and see if there's any interest from anyone else on the team, otherwise I'd be happy to take this one.

Clarifying questions for anyone that might potentially take this:
1. How do you want to handle pages that return "404" or "Page Not Found" dialog? Just pass and keep a log of failed values/page requests after a few retries/waits?
2. What cadence do you want this scheduled at with GitHub Actions (daily, weekly, monthly)?

**Comment by drowninginflowers** [comment]
Here is a fair amount of the code and a workflow to accomplish this: https://github.com/drowninginflowers/pdap_url_cache.git
A few notes:
- Currently, this builds a cache_info.json file from another JSON file then parses it to determine when different URLs will need to be cached. Most recently it was built from test.json; although, a copy of sources.json is included in the repository to build a full cache list from the most recent data here in the mirror. That's all fine, but it would probably be better if it built cache_info.json directly from the airtable data
- Along those line, it's possible to have workflows triggered by external events, so it's probably possible to have new source URLs added to the cache_info.json file whenever a new entry is added to the airtable database
- The workflow is currently scheduled to execute on the first day of each month, but given that the program parses when different URLs need caching it could easily be switched to once a day after any bugs I missed are worked out
- All exceptions are pushed into an Error Log at the moment, but at some point it would make more sense to handle them and update the URL info accordingly
- It takes about 30 seconds to cache each URL when I run it from my own computer. That could probably be improved a bit by calling the Internet Archive API directly instead of using savepagenow. I saw somewhere in the documentation that you can tell the API to schedule tasks itself, so it might be worth looking into. Otherwise, it might be worth altering the program to make multiple calls at once instead of sequentially. Not a huge deal at the moment, but as the size of the dataset grows it'll become a bigger deal.

**Comment by josh-chamberlain** [comment]
@drowninginflowers thanks for this! We'll make a new repo, ask you to submit the code to that (maybe with a suggested change or two), and then we'll set up the GitHub Actions workflow ourselves & handle wiring it up to the other repo (or whatever makes sense). @thejqs says he'll be able to take a look soon, maybe Friday!
